"""Render a ranked daily digest from scored deals (Markdown + HTML email)."""
from __future__ import annotations

import html as _html
from datetime import date, datetime, timezone
from typing import Sequence

from .models import Deal
from .tracking import Tracker


def _line(d: Deal, tracker: Tracker) -> str:
    tag = "🧺" if d.is_essential else "🔥"
    loc = " 📍" if d.is_local else ""
    pct = f"{d.discount_pct:.0f}% off " if d.discount_pct else ""
    merch = f" — {d.merchant}" if d.merchant else ""
    return f"- {tag}{loc} **{pct}**{d.title}{merch}  \n  <{tracker.link(d)}>"


def render_markdown(deals: Sequence[Deal], min_discount: float,
                    per_section: int = 15, affiliate_note: str = "",
                    tracker: Tracker | None = None) -> str:
    tracker = tracker or Tracker(None, "email")
    essentials = [d for d in deals if d.is_essential]
    big = [d for d in deals if not d.is_essential]

    essentials.sort(key=lambda d: d.score, reverse=True)
    big.sort(key=lambda d: d.score, reverse=True)

    lines = [f"# 🛒 Daily Deals — {date.today():%A, %B %d, %Y}", ""]
    lines.append(f"Surfacing essentials on sale and non-essentials at "
                 f"≥{min_discount:.0f}% off. {len(deals)} deals matched today.\n")

    lines.append("## 🧺 Essentials on sale")
    lines += ([_line(d, tracker) for d in essentials[:per_section]]
              or ["- _Nothing today. Widen your essential keywords or lower the "
                  "essential threshold in config.yaml._"])
    lines.append("")

    lines.append(f"## 🔥 Biggest discounts (≥{min_discount:.0f}% off)")
    lines += ([_line(d, tracker) for d in big[:per_section]]
              or ["- _No non-essential deals cleared the threshold today._"])
    lines.append("")

    lines.append("---")
    lines.append("_📍 = local store/restaurant near you.  Generated by DealHunter._")
    lines.append(f"_Prices retrieved {datetime.now(timezone.utc):%b %d, %Y %H:%M UTC}; "
                 f"verify on the merchant page before buying._")
    if affiliate_note:
        lines.append(f"_{affiliate_note}_")
    return "\n".join(lines)


def build_subject(deals: Sequence[Deal]) -> str:
    n_ess = sum(1 for d in deals if d.is_essential)
    n_big = len(deals) - n_ess
    return (f"🛒 Daily Deals — {n_ess} essential"
            f"{'s' if n_ess != 1 else ''} & {n_big} big discount"
            f"{'s' if n_big != 1 else ''} ({date.today():%b %d})")


# ── HTML email rendering (inline styles: required by most email clients) ─────
def _card(d: Deal, tracker: Tracker) -> str:
    badge = "#0a7d33" if d.is_essential else "#c0392b"
    label = "ESSENTIAL" if d.is_essential else "DEAL"
    pin = " · 📍 local" if d.is_local else ""
    pct = f"{d.discount_pct:.0f}% off" if d.discount_pct else "deal"
    merch = (f'<div style="color:#666;font-size:13px;margin-top:2px">'
             f'{_html.escape(d.merchant)}</div>') if d.merchant else ""
    return f"""
    <tr><td style="padding:10px 0;border-bottom:1px solid #eee">
      <span style="background:{badge};color:#fff;font-size:11px;font-weight:700;
                   padding:2px 7px;border-radius:10px;letter-spacing:.5px">
        {label}</span>
      <span style="color:{badge};font-weight:700;font-size:14px;margin-left:6px">
        {pct}</span>
      <span style="color:#999;font-size:12px">{pin}</span>
      <div style="margin-top:4px;font-size:15px;line-height:1.35">
        <a href="{_html.escape(tracker.link(d))}"
           style="color:#1a1a1a;text-decoration:none">{_html.escape(d.title)}</a>
      </div>{merch}
    </td></tr>"""


def _section(title: str, deals: list[Deal], empty: str, tracker: Tracker) -> str:
    rows = "".join(_card(d, tracker) for d in deals) or (
        f'<tr><td style="padding:10px 0;color:#999;font-size:14px">{empty}</td></tr>')
    return f"""
    <h2 style="font-size:17px;margin:26px 0 4px">{title}</h2>
    <table role="presentation" width="100%" cellpadding="0" cellspacing="0"
           style="border-collapse:collapse">{rows}</table>"""


def render_html(deals: Sequence[Deal], min_discount: float,
                per_section: int = 15, affiliate_note: str = "",
                tracker: Tracker | None = None, unsubscribe: bool = False,
                sender_address: str = "") -> str:
    tracker = tracker or Tracker(None, "email")
    essentials = sorted((d for d in deals if d.is_essential),
                        key=lambda d: d.score, reverse=True)[:per_section]
    big = sorted((d for d in deals if not d.is_essential),
                 key=lambda d: d.score, reverse=True)[:per_section]

    retrieved = f"{datetime.now(timezone.utc):%b %d, %Y %H:%M UTC}"
    disclosure = (f'<div style="margin-top:10px;color:#aaa;font-size:11px;'
                  f'line-height:1.5">{_html.escape(affiliate_note)}</div>'
                  if affiliate_note else "")
    # Built as a plain string so the {{{RESEND_UNSUBSCRIBE_URL}}} placeholder
    # survives (an f-string would eat the braces). Resend swaps it per contact.
    unsub = ""
    if unsubscribe:
        addr = ("<br>" + _html.escape(sender_address)) if sender_address else ""
        unsub = ('<div style="margin-top:12px;color:#aaa;font-size:11px;'
                 'line-height:1.5">You are receiving this because you subscribed '
                 'at the Deals Board. '
                 '<a href="{{{RESEND_UNSUBSCRIBE_URL}}}" style="color:#888">'
                 'Unsubscribe</a>.' + addr + '</div>')
    return f"""<!DOCTYPE html>
<html><body style="margin:0;background:#f5f5f5;
      font-family:-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif">
  <table role="presentation" width="100%" cellpadding="0" cellspacing="0">
   <tr><td align="center" style="padding:20px 12px">
    <table role="presentation" width="100%" cellpadding="0" cellspacing="0"
           style="max-width:560px;background:#fff;border-radius:12px;
                  padding:24px;text-align:left">
      <tr><td>
        <div style="font-size:22px;font-weight:800">🛒 Daily Deals</div>
        <div style="color:#666;font-size:14px;margin-top:2px">
          {date.today():%A, %B %d, %Y} · essentials on sale and
          non-essentials ≥{min_discount:.0f}% off · {len(deals)} matched</div>
        {_section("🧺 Essentials on sale", essentials,
                  "Nothing today — widen your essential keywords in scoring.py.",
                  tracker)}
        {_section(f"🔥 Biggest discounts (≥{min_discount:.0f}% off)", big,
                  "No non-essential deals cleared the threshold today.",
                  tracker)}
        <div style="margin-top:26px;color:#aaa;font-size:12px;border-top:1px solid #eee;
                    padding-top:12px">📍 = local store/restaurant near you ·
          Generated by DealHunter<br>Prices retrieved {retrieved}; verify on the
          merchant page before buying.{disclosure}{unsub}</div>
      </td></tr>
    </table>
   </td></tr>
  </table>
</body></html>"""
